version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aura-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - aura-network

  nginx:
    image: nginx:1.19-alpine
    container_name: aura-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - aura-network

  db:
    image: postgres:15
    container_name: aura-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - aura-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - aura-network

networks:
  aura-network:
    driver: bridge

volumes:
  aura-db-data:
    driver: local